name: Generate Weekly Lamb Report

on:
  schedule:
    - cron: '0 23 * * 5'       # every Friday at 23:00 UTC
  workflow_dispatch: {}        # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests python-dotenv openai

      - name: Run report generator
        run: python src/report_generator.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: weekly_lamb_report
          path: weekly_report.md
